//! Dynamic RADIO interrupt dispatcher for BLE ↔ Gazell coexistence.
//!
//! When both BLE and Gazell are enabled, shared interrupts (RADIO, EGU0_SWI0)
//! need runtime dispatch. This module provides the shared state (mode atomics)
//! that the codegen-generated ISR handlers read to route interrupts correctly.
//!
//! **ISR handlers and mode switching functions are generated by the codegen**
//! (`rmk-macro/src/codegen/chip/bind_interrupt.rs`) because they reference
//! both `rmk-gazell-sys` and `nrf-sdc`/`nrf-mpsl`, which are only available
//! in the user's crate context.
//!
//! # Usage (codegen-generated code)
//!
//! ```ignore
//! use rmk::wireless::radio_dispatch::{RADIO_MODE, EGU0_MODE, RadioMode};
//!
//! #[embassy_nrf::pac::interrupt]
//! fn RADIO() {
//!     match RADIO_MODE.load(Ordering::Relaxed) {
//!         RadioMode::GAZELL => unsafe { RADIO_IRQHandler() },
//!         RadioMode::BLE => unsafe { mpsl_raw::MPSL_IRQ_RADIO_Handler() },
//!         _ => {}
//!     }
//! }
//! ```

use core::sync::atomic::AtomicU8;

/// Radio interrupt routing mode.
///
/// Stored in `RADIO_MODE` / `EGU0_MODE` atomics, read by ISR handlers
/// to dispatch to the correct protocol stack.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum RadioMode {
    /// No protocol active — interrupts disabled or ignored.
    Idle = 0,
    /// Nordic Gazell 2.4GHz protocol owns the RADIO.
    Gazell = 1,
    /// BLE (via MPSL/SDC) owns the RADIO.
    Ble = 2,
}

impl RadioMode {
    /// Convert from raw u8 value.
    pub fn from_u8(val: u8) -> Option<Self> {
        match val {
            0 => Some(Self::Idle),
            1 => Some(Self::Gazell),
            2 => Some(Self::Ble),
            _ => None,
        }
    }
}

/// Current owner of the RADIO interrupt.
///
/// 0 = Idle, 1 = Gazell, 2 = BLE (see `RadioMode` enum).
/// Set by mode-switching functions before enabling interrupts.
pub static RADIO_MODE: AtomicU8 = AtomicU8::new(RadioMode::Idle as u8);

/// Current owner of the EGU0_SWI0 interrupt.
///
/// 0 = Idle, 1 = Gazell, 2 = BLE (see `RadioMode` enum).
/// Set by mode-switching functions before enabling interrupts.
pub static EGU0_MODE: AtomicU8 = AtomicU8::new(RadioMode::Idle as u8);

#[cfg(test)]
mod tests {
    use super::*;
    use core::sync::atomic::Ordering;

    #[test]
    fn radio_mode_roundtrip() {
        for mode in [RadioMode::Idle, RadioMode::Gazell, RadioMode::Ble] {
            assert_eq!(RadioMode::from_u8(mode as u8), Some(mode));
        }
        assert_eq!(RadioMode::from_u8(3), None);
        assert_eq!(RadioMode::from_u8(255), None);
    }

    #[test]
    fn radio_mode_static_initial_idle() {
        assert_eq!(RADIO_MODE.load(Ordering::Relaxed), RadioMode::Idle as u8);
        assert_eq!(EGU0_MODE.load(Ordering::Relaxed), RadioMode::Idle as u8);
    }
}
